// Mocks generated by Mockito 5.4.4 from annotations
// in bandait/test/presentation/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bandait/data/network/clock_service.dart' as _i8;
import 'package:bandait/domain/models/song.dart' as _i5;
import 'package:bandait/domain/models/user_profile.dart' as _i7;
import 'package:bandait/domain/repositories/audio_engine.dart' as _i2;
import 'package:bandait/domain/repositories/session_repository.dart' as _i6;
import 'package:bandait/domain/repositories/song_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AudioEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioEngine extends _i1.Mock implements _i2.AudioEngine {
  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void playTick() => super.noSuchMethod(
        Invocation.method(
          #playTick,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void playTock() => super.noSuchMethod(
        Invocation.method(
          #playTock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setGlobalOffset(int? ms) => (super.noSuchMethod(
        Invocation.method(
          #setGlobalOffset,
          [ms],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setBufferLength(int? samples) => (super.noSuchMethod(
        Invocation.method(
          #setBufferLength,
          [samples],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getGlobalOffset() => (super.noSuchMethod(
        Invocation.method(
          #getGlobalOffset,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getBufferLength() => (super.noSuchMethod(
        Invocation.method(
          #getBufferLength,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<double> measureLatency() => (super.noSuchMethod(
        Invocation.method(
          #measureLatency,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
        returnValueForMissingStub: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);
}

/// A class which mocks [SongRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongRepository extends _i1.Mock implements _i4.SongRepository {
  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveSong(_i5.Song? song) => (super.noSuchMethod(
        Invocation.method(
          #saveSong,
          [song],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Song>> getSongs() => (super.noSuchMethod(
        Invocation.method(
          #getSongs,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Song>>.value(<_i5.Song>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.Song>>.value(<_i5.Song>[]),
      ) as _i3.Future<List<_i5.Song>>);

  @override
  _i3.Future<_i5.Song?> getSong(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSong,
          [id],
        ),
        returnValue: _i3.Future<_i5.Song?>.value(),
        returnValueForMissingStub: _i3.Future<_i5.Song?>.value(),
      ) as _i3.Future<_i5.Song?>);

  @override
  _i3.Future<void> deleteSong(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSong,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i5.Song>> watchSongs() => (super.noSuchMethod(
        Invocation.method(
          #watchSongs,
          [],
        ),
        returnValue: _i3.Stream<List<_i5.Song>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i5.Song>>.empty(),
      ) as _i3.Stream<List<_i5.Song>>);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i6.SessionRepository {
  @override
  _i3.Stream<List<_i6.BandSession>> get discoveredSessions =>
      (super.noSuchMethod(
        Invocation.getter(#discoveredSessions),
        returnValue: _i3.Stream<List<_i6.BandSession>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i6.BandSession>>.empty(),
      ) as _i3.Stream<List<_i6.BandSession>>);

  @override
  _i3.Stream<List<String>> get connectedPeers => (super.noSuchMethod(
        Invocation.getter(#connectedPeers),
        returnValue: _i3.Stream<List<String>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<String>>.empty(),
      ) as _i3.Stream<List<String>>);

  @override
  _i3.Stream<int> get latencyStream => (super.noSuchMethod(
        Invocation.getter(#latencyStream),
        returnValue: _i3.Stream<int>.empty(),
        returnValueForMissingStub: _i3.Stream<int>.empty(),
      ) as _i3.Stream<int>);

  @override
  _i3.Stream<bool> get panicStream => (super.noSuchMethod(
        Invocation.getter(#panicStream),
        returnValue: _i3.Stream<bool>.empty(),
        returnValueForMissingStub: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Stream<bool> get isLeaderStream => (super.noSuchMethod(
        Invocation.getter(#isLeaderStream),
        returnValue: _i3.Stream<bool>.empty(),
        returnValueForMissingStub: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  bool get isLeader => (super.noSuchMethod(
        Invocation.getter(#isLeader),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Stream<Map<String, dynamic>> get onSetlistReceived => (super.noSuchMethod(
        Invocation.getter(#onSetlistReceived),
        returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
        returnValueForMissingStub: _i3.Stream<Map<String, dynamic>>.empty(),
      ) as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Future<void> startHosting({
    required String? sessionName,
    required int? port,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startHosting,
          [],
          {
            #sessionName: sessionName,
            #port: port,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopHosting() => (super.noSuchMethod(
        Invocation.method(
          #stopHosting,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> startDiscovery() => (super.noSuchMethod(
        Invocation.method(
          #startDiscovery,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopDiscovery() => (super.noSuchMethod(
        Invocation.method(
          #stopDiscovery,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> connectTo(
    String? host,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectTo,
          [
            host,
            port,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void sendPanic() => super.noSuchMethod(
        Invocation.method(
          #sendPanic,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startMetronome(double? bpm) => super.noSuchMethod(
        Invocation.method(
          #startMetronome,
          [bpm],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopMetronome() => super.noSuchMethod(
        Invocation.method(
          #stopMetronome,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> saveUserProfile(_i7.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i7.UserProfile?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i3.Future<_i7.UserProfile?>.value(),
        returnValueForMissingStub: _i3.Future<_i7.UserProfile?>.value(),
      ) as _i3.Future<_i7.UserProfile?>);

  @override
  void broadcastSetlist(Map<String, dynamic>? setlistJson) =>
      super.noSuchMethod(
        Invocation.method(
          #broadcastSetlist,
          [setlistJson],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ClockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClockService extends _i1.Mock implements _i8.ClockService {
  @override
  bool get isSynced => (super.noSuchMethod(
        Invocation.getter(#isSynced),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get offset => (super.noSuchMethod(
        Invocation.getter(#offset),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Stream<int> get beatStream => (super.noSuchMethod(
        Invocation.getter(#beatStream),
        returnValue: _i3.Stream<int>.empty(),
        returnValueForMissingStub: _i3.Stream<int>.empty(),
      ) as _i3.Stream<int>);

  @override
  int now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void startMetronome(
    double? bpm,
    int? startTime,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #startMetronome,
          [
            bpm,
            startTime,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopMetronome() => super.noSuchMethod(
        Invocation.method(
          #stopMetronome,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleSyncResponse(
    int? t1,
    int? t2,
    int? t3,
    int? t4,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleSyncResponse,
          [
            t1,
            t2,
            t3,
            t4,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
