name: bandait
description: Bandait - Multiplatform synchronization system for live musicians.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # DI
  get_it: ^7.6.0
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
